// <auto-generated />
using System;
using Friday.Modules.Salon.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Friday.Modules.Salon.Infrastructure.Migrations
{
    [DbContext(typeof(SalonDbContext))]
    [Migration("20260530120000_MChair_Partners")]
    partial class MChair_Partners
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");
#pragma warning restore 612, 618
        }
    }
}
